# Site settings
title: Lionel's blog
email: ckmessi@163.com
description: > # this means to ignore newlines until "baseurl:"
  copyright@Lionel 2015
baseurl: "/blog-jekyll" # the subpath of your site, e.g. /blog/
url: "http://github.ckmessi.io" # the base hostname & protocol for your site
github_username:  ckmessi
# Build settings
markdown: kramdown
